apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: backend-ns
  labels:
    app: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: demowebappregistry.azurecr.io/demowebappimage:v1
        ports: 
        - containerPort: 80
        env:
        - name: MSSQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: mssql-config
              key: mssql-server
        - name: MSSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mssql-config
              key: mssql-port
        - name: MSSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mssql-secret-backend
              key: mssql-pass

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: backend-ns
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - name: webapp-port
    protocol: TCP
    port: 8080
    targetPort: 80
